### ISSUE TITLE
关于windows下盘跨越的问题？

### ISSUE THREAD

**Issue by T4di5** [mjpclab/go-http-file-server#1]
大佬，在默认情况，只能返回到当前绝对路径的根磁盘，例如D:/111/bbb/ccc.txt，就只能回到D:
可以跨越到C盘/F盘么？

**Comment by marjune163** [comment]
目前的变通办法是使用空根目录(`-R`)，并挂载所有的分区到根URL或子路径，例如：
```cmd
ghfs -R -a #DriveC#C:\ #DriveD#D:\ #DriveE#E:\
```
这样页面根下面就会有DriveC, DriveD, DriveE。
