### ISSUE TITLE
无法上传

### ISSUE THREAD

**Issue by wangdemon** [mjpclab/go-http-file-server#15]
通过命令行参数--u,设置上传目录，但是打开浏览器后，没有看到上传按钮
![1](https://user-images.githubusercontent.com/20681339/158057636-3ac63b5d-6ed0-43ac-9d3d-be68c4f59fc6.PNG)
![2](https://user-images.githubusercontent.com/20681339/158057640-23e87272-f04b-4046-9e23-2071d7713dd4.PNG)

**Comment by marjune163** [comment]
`-U` 为大写

**Comment by marjune163** [comment]
`-u` 或 `--upload` 指定URL路径，如是文件系统路径，应该使用`--upload-dir`。

例如
- `-u /11` 开启 http://ip/11 目录的上传
- `-r D:\data --upload-dir D:\Data\11` 开启 http://ip/11 目录的上传

**Comment by wangdemon** [comment]
懂了，老哥。您的代码太强了。我看到另一个仓库(https://github.com/bitepeng/b0pass)，和您的这个项目，有异曲同工之妙。但是我觉得您的这个项目做的更好。
