### ISSUE TITLE
这是我今年看到开源最棒的作品

### ISSUE THREAD

**Issue by wangdemon** [mjpclab/go-http-file-server#16]
这个开源项目，是我见过最棒的作品，比飞秋传输工具还要强大。在使用过程中，发现有些不友好的：
（1）拖拽一个文件夹上传时，只把文件夹中第一级子目录的文件上传了，文件夹的第二级子目录，第三级子目录等都没有上传；
（2）上传文件夹完成后，发现服务器中的存储的文件，不能按照文件夹中的层级关系存储；
（3）上传文件过程中，没有上传速度和百分比显示。

**Comment by marjune163** [comment]
感谢支持，如需上传多层目录，需要同时建目录`--mkdir`的选项。目前最新版本可以在页面顶部看到总体进度条，由于实现原理的关系，暂时看不到单个文件的进度。再次感谢反馈~
