### ISSUE TITLE
[Feature request] Drag and drop upload folder

### ISSUE THREAD

**Issue by meav** [mjpclab/go-http-file-server#2]
First of all, thank you very much because awesome project.
I think upload folder is very useful feature. I hope you will add this feature in future.
Sorry for my bad english.

**Comment by marjune163** [comment]
Thanks for your suggestion. I will look into it.

**Comment by marjune163** [comment]
There is no standard way to upload directories via web browser. But currently Chromium based and Firefox based browsers supports an [experimental feature](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory) `webkitdirectory`, allow user to upload all contents of a single directory:  

Dargging directories to upload area is still not supported.

I will apply the experimental feature to allow user uploding a single directory by click the upload input box, which all contents within it will be uploaded to current server directory. If the server directory uploading to has no `mkdir` option set, will ignore uploaded subdirectory contents.

Also there is [a nnew proposal for uploading directories](https://wicg.github.io/directory-upload/proposal.html), but it is not standardized, and no browser implemented yet.

**Comment by marjune163** [comment]
Implement on version 1.10.0

**Comment by meav** [comment]
![Untitled](https://user-images.githubusercontent.com/29623675/101799293-93e1ec00-3b3e-11eb-9b10-b00f4c9bbb65.png)
It work like a champ, this is all I need, thank you very much.
I think you should remove tab Dir content.
And this issue can be closed.

**Comment by marjune163** [comment]
I prefer to keep "Dir contents", which allow to upload files and sub directories inside the selected directory. Sometimes it is useful.

**Comment by marjune163** [comment]
After further investigation, there is a way to upload directories by drag and drop. It is now release as version 1.10.6. Let me know if there is any issue.

**Comment by meav** [comment]
Amazing!
Just one suggestion: This is wonderful feature, you should add this to gif file in Readme.md
