### ISSUE TITLE
global-mkdir命令开启的问题

### ISSUE THREAD

**Issue by wangdemon** [mjpclab/go-http-file-server#21]
大佬，我使用--global-mkdir命令后，确实可以将包含子文件及子文件夹的的文件夹一起上传，但是子文件超过100个，也只能上传100个

**Comment by marjune163** [comment]
我试下来没问题呢，是不是磁盘满了？

**Comment by wangdemon** [comment]
可以看下面视频，在wins系统，我有三个文件夹，每个文件夹中有114张png图片，上传到ubuntu服务后，每个文件夹中，只有100张png图片。

https://user-images.githubusercontent.com/20681339/177304185-161a21d4-91ae-4305-a4bb-8554928ae3f1.mp4

**Comment by marjune163** [comment]
一般图标大小是多少呢？

**Comment by wangdemon** [comment]
是的，您说的对。谷歌浏览器确实有限制，火狐浏览器上传文件没有问题。

**Comment by marjune163** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryReader/readEntries

> On Chrome 77, readEntries() will only return the first 100 FileSystemEntry instances. In order to obtain all of the instances, readEntries() must be called multiple times.

**Comment by wangdemon** [comment]
感谢老哥无私奉献

**Comment by marjune163** [comment]
下一版会修复的。

**Comment by marjune163** [comment]
已在1.14.0中修复。

**Comment by wangdemon** [comment]
谢谢您，老哥真的很用心！

**Comment by wangdemon** [comment]
hfs 1.14.0版本，在str.go文件中，使用了utf8.AppendRune(buf, r)，这个函数好像在golang 1.18中才有。我的go1.17版本，编译不过，升级到go的最新版，就编译过了。

**Comment by marjune163** [comment]
嗯，看来要更新下Readme了，多谢。
