### ISSUE TITLE
当设置密码认证之后，手机端就无法下载了

### ISSUE THREAD

**Issue by chs72** [mjpclab/go-http-file-server#22]
当设置密码认证之后，手机端就无法下载，或者下载下来是0kb，测试了miui浏览器、Alook以及Chrome，只有Chrome可以。

另外，请问会增加搜索功能吗

**Comment by marjune163** [comment]
我这边用Alook Android版测试下来没问题。看看是不是哪里有安全设置阻止了认证信息的发送。
