### ISSUE TITLE
1.15.12版本，通过浏览器删除文件失败

### ISSUE THREAD

**Issue by wangdemon** [mjpclab/go-http-file-server#32]
1.15.12版本，通过浏览器删除文件后，显示删除成功，但是刷新浏览器后，文件又显示了。应该是程序没有删除。

**Comment by marjune163** [comment]
有没有什么错误日志？看看是不是权限不够。

**Comment by wangdemon** [comment]
应该是权限问题，我将http-file-server部署在我的腾讯云主机上，出现了文件删除失败，但是我刚才在本地主机上尝试了一下，删除都成功了。
