### ISSUE TITLE
role based access control

### ISSUE THREAD

**Issue by steven-sun** [mjpclab/go-http-file-server#36]
真不错！
请问是否能支持根据角色进行权限管理，认证采用header，jwt或其他常用形式，这样就能集成到更多需要文件管理的项目里。

**Comment by marjune163** [comment]
目前暂未支持，但是可以在自己的项目里添加认证功能，然后以中间件的方式调用ghfs，示例：
https://github.com/mjpclab/use-ghfs-example/blob/main/use-as-middleware.go
