### ISSUE TITLE
Can't open directories which contain `%2F` in them names

### ISSUE THREAD

**Issue by eitsupi** [mjpclab/go-http-file-server#4]
Thank you for this great project.

When I was using `ghfs` in combination with other software, I noticed that I could not open directries with `%2F` in the name (https://github.com/ktaaaki/paper2html/pull/21#issuecomment-791909131).
`%2F` seems to be interpreted as slash `/` on the server.

![image](https://user-images.githubusercontent.com/50911393/110204349-df920080-7eb5-11eb-911d-87cf82c64059.png)

**Comment by marjune163** [comment]
Hey, thanks for your reporting. It is now fixed and released as v1.10.13.
Thanks a lot!
