### ISSUE TITLE
Suggestion: No-index on some folders, per dir per user

### ISSUE THREAD

**Issue by fimmspin** [mjpclab/go-http-file-server#42]
New feature to add could be to show a blank-dir with no file index/contents (this setting will be per-dir-per-user).
A user can download files only if he knows the exact filename to download, or can upload a file to this 'blank-dir' (but all files in that dir will be visible only to enabled users only).
This will permit to create an 'uploads' folder keeping files hidden by unwanted eyes of other users.
Or to send a file dowload link to someone without the possibility he will see the full directory contents.

**Comment by marjune163** [comment]
Please try `--hide '*'` but uploaded files also not visible.

**Comment by marjune163** [comment]
For version 1.18.0, you could use:

```
ghfs --index "" --index-users :/upload:admin1:admin2:admin3 ...
```
