### ISSUE TITLE
有什么办法可以直接点击下载可以直接用浏览器打开的文件呢？

### ISSUE THREAD

**Issue by lie5860** [mjpclab/go-http-file-server#47]
默认情况下上传一个 txt，在 web chrome 上点击这个 txt 会直接在网页打开这个文件。希望有办法点击可以直接下载。不知道目前是否已经支持。

**Comment by marjune163** [comment]
在文件URL后追加`?downloadfile`可直接下载文件。

在目录列表页URL后追加`?downloadfile`会使列出的文件都自动追加。

**Comment by lie5860** [comment]
> 在文件URL后追加`?downloadfile`可直接下载文件。
> 
> 在目录列表页URL后追加`?downloadfile`会使列出的文件都自动追加。

这个在目录列表页URL后追加确实可以。但是这样就不能上传文件和去上一级目录和删除文件了。有一丢丢不方便但也能用。如果 有参数能控制列表单个文件的 href 就好了。

**Comment by marjune163** [comment]
下一个版本会改成用`?simple`代表精简页面，`?download`代表文件可下载，`?simpledownload`包含两者。
目前在unstable分支上。

**Comment by lie5860** [comment]
> 下一个版本会改成用`?simple`代表精简页面，`?download`代表文件可下载，`?simpledownload`包含两者。 目前在unstable分支上。

好的感谢

**Comment by marjune163** [comment]
1.20.0已经支持了。https://github.com/mjpclab/go-http-file-server/blob/main/doc/zh-CN/api.md#%E6%98%BE%E7%A4%BA%E7%B2%BE%E7%AE%80%E9%A1%B5%E9%9D%A2
